### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to write reviews/posts, and interact with other users by liking, sharing, or commenting on their posts.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/181084164-16c739d3-a3d7-4646-aef5-ec71cf092654.png)
![image](https://user-images.githubusercontent.com/103145813/181084206-2b1748f2-1e66-4408-bc3d-0cca30b95c59.png)
![image](https://user-images.githubusercontent.com/103145813/181084249-2926c15b-9c75-42ed-ab13-1d73872b5386.png)
![image](https://user-images.githubusercontent.com/103145813/181084301-fbfbf009-a103-472f-9857-d64df27ce5ef.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create a 'users' table
- [x] Update `data.sql` to insert dummy data

### ☁️ Server Tasks

- [x] Update `server/index.js` to make a GET request to the 'users' table
- [x] Update `server/index.js` to make a POST request to the 'users' table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a main page to sign-in/option to sign-up
- [x] Create a page to sign-up
- [x] Create a page to update user profile
- [x] Create hash routing to switch from sign-in page > sign-up page > update profile page
- [x] Clicking logo takes user back to sign-in page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by calvin-tran1** [comment]
![chrome_XvxaC9FGhX](https://user-images.githubusercontent.com/103145813/181620876-db10764b-ba48-424c-aa1f-3a6ca3e379d4.gif)
