### ISSUE TITLE
Feature: User can sign in/sign out

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/181626325-7752eb59-cc49-4a32-821c-1d03faf86e99.png)
![image](https://user-images.githubusercontent.com/103145813/181626395-91ebf88c-e731-429d-a9cf-62d9c6c9bc81.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Sign up route generates token

### ⚡ Client Tasks

- [x] Sign user in immediately after registration, and redirect them to profile setup
- [x] Create a home page
- [x] User is redirected to the home page upon profile completion
- [x] Create components for the sidebars on desktop view
- [x] Create a component for the top navbar for mobile view
- [x] Create a component for the bottom navbar for mobile view
- [x] Render user data to the applicable components
- [x] Clicking user avatar gives the user an option to sign out
- [x] Clicking sign out removes credentials from local storage and returns user to the sign in page

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
