### ISSUE TITLE
Feature: User can write a post

### ISSUE THREAD

**Issue by calvin-tran1** [calvin-tran1/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103145813/182437099-6ec87b66-865a-4a88-b141-cec8da793902.png)
![image](https://user-images.githubusercontent.com/103145813/182437254-cd3595ac-1192-4fa8-9c7e-810b3eadfebc.png)
![image](https://user-images.githubusercontent.com/103145813/182437381-5a4b6189-6f60-4e94-81e2-c36ddd4ef834.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to make POST requests to the posts table of the database
- [x] Update `server/index.js` to make GET requests to the posts table of the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Make post buttons interactive on mobile/desktop views
- [x] Create a component to create a post on desktop view
- [x] Create a page to create a post on mobile view
- [x] Create a page to view your user profile
- [x] Create a component for cards holding posts
- [x] Render data accordingly to the necessary components/pages

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
